import { Country, CommentItem } from './types';

export const INITIAL_COMMENTS: CommentItem[] = [
  { id: 'c1', text: 'SPLF - False SPL Match- Customer and RPL are different. Two Different Individuals', category: 'General' },
  { id: 'c2', text: 'SPLF - False SPL Match- Customer and RPL are different.Both the Country are different.', category: 'General' },
  { id: 'c3', text: 'SPLF - False SPL Match- Customer name match that of the RPL name. The address is different.', category: 'General' },
  { id: 'c4', text: 'SPLF - False SPL Match- Customer and RPL are different. Individual vs Entity.', category: 'General' },
  { id: 'c5', text: 'SPLF - False SPL Match- Customer and RPL are different.', category: 'General' },
  { id: 'c6', text: 'SPLE -Eligible for SPL Exemption - The customer is an HP entity and qualifies for an exemption.', category: 'General' },
  { id: 'c7', text: 'APRV - Released as per MDCP Process Chart - Conditional Hold', category: 'General' },
  { id: 'c8', text: 'APSP- Approved by GT Trade Compliance as simplified NPS process- CDAX order', category: 'General' },
  { id: 'c9', text: 'NPSE - Eligible for NPS Exemption - The customer is a US Government Agency and qualifies for an exemption.', category: 'General' },
  { id: 'c10', text: 'NPSE - Eligible for NPS Exemption - The customer is located in the US and qualifies for an exemption.', category: 'General' },
  { id: 'c11', text: 'KWDF- False Keyword Match - XXXX was the keyword that matched the customer’s name. This customer does not participate in activities of concern. See website: WWW.XXXX', category: 'General' },
  { id: 'c12', text: 'NPSA - NPS OK all Locations -Screening ID# NPxxxxxxxx with green/white status.', category: 'General' },
  { id: 'c13', text: 'NPST - NPS OK this Locations -Screening ID# NPxxxxxxxx with green/white status.', category: 'General' },
  { id: 'c14', text: 'EMBF - False ZEMB Match - Our customer is in the business of See website:', category: 'General' },
  { id: 'c15', text: 'EMBF - False ZEMB Match - Locked is the individual Person and not related to embargo country.', category: 'General' },
  { id: 'c16', text: 'EMBN - Delivery to Non-Embargoed Country-Embassy of a non-embargoed country in a non-embargoed country.', category: 'General' },
  { id: 'c17', text: 'EMBN - Delivery to Non-Embargoed Country-Consulate of a non-embargoed country in a non-embargoed country.', category: 'General' },
];

export const INITIAL_APRV_COMMENTS: CommentItem[] = [
  { 
    id: 'aprv1', 
    title: 'HUAWEI CHINA / LIKP (deliveries)', 
    text: 'APRV-SO previously authorized per US License.\nApproved by bridget.kat.van-herp@hp.com\nDated on Tuesday, March 29, 2022 10:41AM', 
    additionalInfo: 'The rest of orders on Huawei for all countries are escalated to Bridget',
    category: 'APRV' 
  },
  { 
    id: 'aprv2', 
    title: 'ICSO', 
    text: 'Approval from Mark (Export compliance officer) exempting ICSOs from reconciliation.\nApproval renewed on May 1st 2025 as interim solution.',
    additionalInfo: 'ICSO that are exact matches are to be released using the same approval used for the SO stating that relation in the comment.',
    remarks: 'Dtype-ZIC/ZDC', 
    category: 'APRV' 
  },
  { 
    id: 'aprv3', 
    title: 'ZYME (Only for SPLF) Can be applied for multiple lines', 
    text: 'APPRV-Approval from Nestor Quiñones (TC Director) and Mark Burleson (Export compliance officer) To Release transaction on hold as an interim solution. June 2nd-2025',
    additionalInfo: 'Exact matches, CNUEL, Huawei are NOT included here',
    remarks: 'This approval will apply only for missing country and Address for False match cases.', 
    category: 'APRV' 
  },
  { 
    id: 'aprv4', 
    title: 'BUSINESS PARTNERS (MDCP02) Conditional holds', 
    text: 'APRV - Released as per MDCP Process Chart - Conditional Hold',
    additionalInfo: 'All the exact matches that are conditional holds and under this logical system, can be released.\nMDCP02 is a logical system for Customers.',
    remarks: 'CN customers needs to be escalatd to language experts(Pratik/Lija)', 
    category: 'APRV' 
  },
  { 
    id: 'aprv5', 
    title: 'CNUEL - BAE Systems PLC', 
    text: 'APRV.- Nov 04th ,2024- Customer "BAE Systems plc" (to be filled with customer’s name), has no relation with BAE Systems Land an Armament, OK to release, per Export Compliance team (Bridget).',
    additionalInfo: 'Handled by the entire Team',
    remarks: 'This approval will apply for Sales Orders(BUS2032) & Delivery Orders (LIKP)', 
    category: 'APRV' 
  },
  { 
    id: 'aprv6', 
    title: 'CNUEL - Contracts', 
    text: 'APPRV-Confirmed by Bridget Van Herp in meeting May 5th-\nThere is not a shipment involved on Contracts, it can be released.\nSent: Monday, May 6, 2024 12:21 PM',
    additionalInfo: 'Handled by the entire Team',
    remarks: 'Only for Contract (BUS2034)', 
    category: 'APRV' 
  },
  { 
    id: 'aprv7', 
    title: 'CN UEL - ZYME', 
    text: 'ZYME – This screening is to only release compensation to Business Partners based on a review of end customers visible to HP.\nThere is no physical export to these end customers.\nFrom: Bridget VanHerp April 9th 2024',
    additionalInfo: 'Handled by the entire Team', 
    category: 'APRV' 
  },
  { 
    id: 'aprv8', 
    title: 'CN UEL - Teradici', 
    text: 'APRVD-From: Van Herp, Bridget <bridget.kat.van-herp@hp.com>\nSent: Wednesday, January 22, 2025 12:30 PM-\nApprove to release CN UEL / TERADICI PARTNERS, the server is not in CN.',
    additionalInfo: 'Handled by the entire Team\nTeradici manages software to be downloaded by the customer, the server is in US', 
    category: 'APRV' 
  },
  { 
    id: 'aprv9', 
    title: 'CN UEL - PDAPI Customers', 
    text: 'APRVD-From: Van Herp, Bridget <bridget.kat.van-herp@hp.com>\nSent: Wednesday, January 22, 2025 12:28 PM-\nApprove to release CN UEL / PDAPI CUSTOMERS. This is approved for SW licenses being delivered virtually.',
    additionalInfo: 'Handled by the entire Team\nPDAP also manages software to be downloaded by the customer, the server is in US.', 
    category: 'APRV' 
  },
  { 
    id: 'aprv10', 
    title: 'CN UEL - MONETA', 
    text: 'Moneta – This screening is only to release business partner holds to be able to bill customers for Instant Ink subscriptions. There is no physical export by releasing the business partner. If there is any physical export a sales order is created in GTS separately and is screened through GTS.\nFrom: Bridget VanHerp April 9th 2024',
    additionalInfo: 'Handled by the entire Team', 
    category: 'APRV' 
  },
  { 
    id: 'aprv11', 
    title: 'CN UEL - MMDCP12', 
    text: 'APRV -Released as per MDCP Process Chart - Conditional Hold/ This approval of MDCP 12 is going to be only for CN UEL customers.\nFrom: Van Herp, Bridget bridget.kat.van-herp@hp.com\nSent: Monday, January 6, 2025 2:47 PM',
    additionalInfo: 'Handled by the entire Team',
    remarks: 'Only for conditional hold', 
    category: 'APRV' 
  },
  { 
    id: 'aprv12', 
    title: 'RU Reseller', 
    text: 'Approval granted by Nestor Quinones (Head of Trade Compliance and Legal Counsel) to release transactions previously placed on hold due to deal/reseller screening, under the condition that all business partners involved in the transaction have been fully screened and pose no compliance risk, and there is no evidence indicating that the reseller responsible for the hold is participating in the transaction. Valid from 09/01/2025.',
    additionalInfo: 'Handled by the entire Team',
    remarks: 'RU resellers along with Exact match cases needs to be escalated for approvals.', 
    category: 'APRV' 
  },
];

export const COUNTRIES: Country[] = [
  // EMEA Region
  { name: 'Algeria', code: 'DZ', region: 'EMEA' },
  { name: 'Angola', code: 'AO', region: 'EMEA' },
  { name: 'Ascension', code: 'SH', region: 'EMEA' },
  { name: 'Benin', code: 'BJ', region: 'EMEA' },
  { name: 'Botswana', code: 'BW', region: 'EMEA' },
  { name: 'Burkina Faso', code: 'BF', region: 'EMEA' },
  { name: 'Burundi', code: 'BI', region: 'EMEA' },
  { name: 'Cameroon', code: 'CM', region: 'EMEA' },
  { name: 'Cape Verde Islands', code: 'CV', region: 'EMEA' },
  { name: 'Central African Republic', code: 'CF', region: 'EMEA' },
  { name: 'Chad Republic', code: 'TD', region: 'EMEA' },
  { name: 'Comoros', code: 'KM', region: 'EMEA' },
  { name: 'Congo', code: 'CG', region: 'EMEA' },
  { name: 'Djibouti', code: 'DJ', region: 'EMEA' },
  { name: 'Egypt', code: 'EG', region: 'EMEA' },
  { name: 'Equatorial Guinea', code: 'GQ', region: 'EMEA' },
  { name: 'Eritrea', code: 'ER', region: 'EMEA' },
  { name: 'Ethiopia', code: 'ET', region: 'EMEA' },
  { name: 'Gabon Republic', code: 'GA', region: 'EMEA' },
  { name: 'Gambia', code: 'GM', region: 'EMEA' },
  { name: 'Ghana', code: 'GH', region: 'EMEA' },
  { name: 'Guinea-Bissau', code: 'GW', region: 'EMEA' },
  { name: 'Guinea', code: 'GN', region: 'EMEA' },
  { name: 'Ivory Coast', code: 'CI', region: 'EMEA' },
  { name: 'Kenya', code: 'KE', region: 'EMEA' },
  { name: 'Lesotho', code: 'LS', region: 'EMEA' },
  { name: 'Liberia', code: 'LR', region: 'EMEA' },
  { name: 'Libya', code: 'LY', region: 'EMEA' },
  { name: 'Madagascar', code: 'MG', region: 'EMEA' },
  { name: 'Malawi', code: 'MW', region: 'EMEA' },
  { name: 'Mali Republic', code: 'ML', region: 'EMEA' },
  { name: 'Mauritania', code: 'MR', region: 'EMEA' },
  { name: 'Mauritius', code: 'MU', region: 'EMEA' },
  { name: 'Mayotte Island', code: 'YT', region: 'EMEA' },
  { name: 'Morocco', code: 'MA', region: 'EMEA' },
  { name: 'Mozambique', code: 'MZ', region: 'EMEA' },
  { name: 'Namibia', code: 'NA', region: 'EMEA' },
  { name: 'Niger Republic', code: 'NE', region: 'EMEA' },
  { name: 'Nigeria', code: 'NG', region: 'EMEA' },
  { name: 'Principe', code: 'ST', region: 'EMEA' },
  { name: 'Reunion Island', code: 'RE', region: 'EMEA' },
  { name: 'Rwanda', code: 'RW', region: 'EMEA' },
  { name: 'Sao Tome', code: 'ST', region: 'EMEA' },
  { name: 'Senegal Republic', code: 'SN', region: 'EMEA' },
  { name: 'Seychelles', code: 'SC', region: 'EMEA' },
  { name: 'Sierra Leone', code: 'SL', region: 'EMEA' },
  { name: 'Somalia Republic', code: 'SO', region: 'EMEA' },
  { name: 'South Africa', code: 'ZA', region: 'EMEA' },
  { name: 'St. Helena', code: 'SH', region: 'EMEA' },
  { name: 'Sudan', code: 'SD', region: 'EMEA' },
  { name: 'Swaziland', code: 'SZ', region: 'EMEA' },
  { name: 'Tanzania', code: 'TZ', region: 'EMEA' },
  { name: 'Togo', code: 'TG', region: 'EMEA' },
  { name: 'Tunisia', code: 'TN', region: 'EMEA' },
  { name: 'Uganda', code: 'UG', region: 'EMEA' },
  { name: 'Zaire', code: 'CD', region: 'EMEA' },
  { name: 'Zambia', code: 'ZM', region: 'EMEA' },
  { name: 'Zanzibar', code: 'TZ', region: 'EMEA' },
  { name: 'Zimbabwe', code: 'ZW', region: 'EMEA' },
  { name: 'South Sudan', code: 'SS', region: 'EMEA' },
  { name: 'Dem. Republic of the Congo', code: 'CD', region: 'EMEA' },
  { name: 'Albania', code: 'AL', region: 'EMEA' },
  { name: 'Andorra', code: 'AD', region: 'EMEA' },
  { name: 'Austria', code: 'AT', region: 'EMEA' },
  { name: 'Belarus', code: 'BY', region: 'EMEA' },
  { name: 'Belgium', code: 'BE', region: 'EMEA' },
  { name: 'Bosnia and Herzegovina', code: 'BA', region: 'EMEA' },
  { name: 'Bulgaria', code: 'BG', region: 'EMEA' },
  { name: 'Croatia', code: 'HR', region: 'EMEA' },
  { name: 'Cyprus', code: 'CY', region: 'EMEA' },
  { name: 'Czech Republic', code: 'CZ', region: 'EMEA' },
  { name: 'Denmark', code: 'DK', region: 'EMEA' },
  { name: 'Estonia', code: 'EE', region: 'EMEA' },
  { name: 'Faroe Islands', code: 'FO', region: 'EMEA' },
  { name: 'Finland', code: 'FI', region: 'EMEA' },
  { name: 'France', code: 'FR', region: 'EMEA' },
  { name: 'Germany', code: 'DE', region: 'EMEA' },
  { name: 'Gibraltar', code: 'GI', region: 'EMEA' },
  { name: 'Greece', code: 'GR', region: 'EMEA' },
  { name: 'Hungary', code: 'HU', region: 'EMEA' },
  { name: 'Iceland', code: 'IS', region: 'EMEA' },
  { name: 'Ireland', code: 'IE', region: 'EMEA' },
  { name: 'Italy', code: 'IT', region: 'EMEA' },
  { name: 'Latvia', code: 'LV', region: 'EMEA' },
  { name: 'Liechtenstein', code: 'LI', region: 'EMEA' },
  { name: 'Lithuania', code: 'LT', region: 'EMEA' },
  { name: 'Luxembourg', code: 'LU', region: 'EMEA' },
  { name: 'Macedonia', code: 'MK', region: 'EMEA' },
  { name: 'Malta', code: 'MT', region: 'EMEA' },
  { name: 'Moldova', code: 'MD', region: 'EMEA' },
  { name: 'Monaco', code: 'MC', region: 'EMEA' },
  { name: 'Netherlands', code: 'NL', region: 'EMEA' },
  { name: 'Norway', code: 'NO', region: 'EMEA' },
  { name: 'Poland', code: 'PL', region: 'EMEA' },
  { name: 'Portugal', code: 'PT', region: 'EMEA' },
  { name: 'Romania', code: 'RO', region: 'EMEA' },
  { name: 'Russia', code: 'RU', region: 'EMEA' },
  { name: 'San Marino', code: 'SM', region: 'EMEA' },
  { name: 'Serbia', code: 'RS', region: 'EMEA' },
  { name: 'Slovakia', code: 'SK', region: 'EMEA' },
  { name: 'Slovenia', code: 'SI', region: 'EMEA' },
  { name: 'Spain', code: 'ES', region: 'EMEA' },
  { name: 'Sweden', code: 'SE', region: 'EMEA' },
  { name: 'Switzerland', code: 'CH', region: 'EMEA' },
  { name: 'Ukraine', code: 'UA', region: 'EMEA' },
  { name: 'United Kingdom', code: 'GB', region: 'EMEA' },
  { name: 'Vatican city', code: 'VA', region: 'EMEA' },
  { name: 'Yugoslavia', code: 'RS', region: 'EMEA' },
  { name: 'Isle of Man', code: 'IM', region: 'EMEA' },
  { name: 'Kosovo', code: 'RS', region: 'EMEA' },
  { name: 'Montenegro', code: 'ME', region: 'EMEA' },

  // APJ Region
  { name: 'American Samoa', code: 'AS', region: 'APJ' },
  { name: 'Australia', code: 'AU', region: 'APJ' },
  { name: 'Chatham Island, NZ', code: 'NZ', region: 'APJ' },
  { name: 'Cook Islands', code: 'CK', region: 'APJ' },
  { name: 'Fiji Islands', code: 'FJ', region: 'APJ' },
  { name: 'French Polynesia', code: 'PF', region: 'APJ' },
  { name: 'Guam', code: 'GU', region: 'APJ' },
  { name: 'Kiribati', code: 'KI', region: 'APJ' },
  { name: 'Mariana Islands', code: 'MP', region: 'APJ' },
  { name: 'Marshall Islands', code: 'MH', region: 'APJ' },
  { name: 'Federated States of Micronesia', code: 'FM', region: 'APJ' },
  { name: 'Midway Islands', code: 'UM', region: 'APJ' },
  { name: 'Nauru', code: 'NR', region: 'APJ' },
  { name: 'New Caledonia', code: 'NC', region: 'APJ' },
  { name: 'New Zealand', code: 'NZ', region: 'APJ' },
  { name: 'Niue', code: 'NU', region: 'APJ' },
  { name: 'Norfolk Island', code: 'NF', region: 'APJ' },
  { name: 'Palau', code: 'PW', region: 'APJ' },
  { name: 'Papua New Guinea', code: 'PG', region: 'APJ' },
  { name: 'Saipan', code: 'MP', region: 'APJ' },
  { name: 'Solomon Islands', code: 'SB', region: 'APJ' },
  { name: 'Tokelau', code: 'TK', region: 'APJ' },
  { name: 'Tonga', code: 'TO', region: 'APJ' },
  { name: 'Tuvalu', code: 'TV', region: 'APJ' },
  { name: 'Vanuatu', code: 'VU', region: 'APJ' },
  { name: 'Wake Island', code: 'UM', region: 'APJ' },
  { name: 'Wallis and Futuna Islands', code: 'WF', region: 'APJ' },
  { name: 'Samoa', code: 'WS', region: 'APJ' },
  { name: 'East Timor', code: 'TL', region: 'APJ' },
  { name: 'Afghanistan', code: 'AF', region: 'APJ' },
  { name: 'Armenia', code: 'AM', region: 'APJ' },
  { name: 'Azerbaijan', code: 'AZ', region: 'APJ' },
  { name: 'Bahrain', code: 'BH', region: 'APJ' },
  { name: 'Bangladesh', code: 'BD', region: 'APJ' },
  { name: 'Bhutan', code: 'BT', region: 'APJ' },
  { name: 'Brunei', code: 'BN', region: 'APJ' },
  { name: 'Cambodia', code: 'KH', region: 'APJ' },
  { name: 'China', code: 'CN', region: 'APJ' },
  { name: 'Christmas Island', code: 'CX', region: 'APJ' },
  { name: 'Cocos Islands', code: 'CC', region: 'APJ' },
  { name: 'Diego Garcia', code: 'IO', region: 'APJ' },
  { name: 'Georgia', code: 'GE', region: 'APJ' },
  { name: 'Hong Kong', code: 'HK', region: 'APJ' },
  { name: 'India', code: 'IN', region: 'APJ' },
  { name: 'Indonesia', code: 'ID', region: 'APJ' },
  { name: 'Iran', code: 'IR', region: 'APJ' },
  { name: 'Iraq', code: 'IQ', region: 'APJ' },
  { name: 'Israel', code: 'IL', region: 'APJ' },
  { name: 'Japan', code: 'JP', region: 'APJ' },
  { name: 'Jordan', code: 'JO', region: 'APJ' },
  { name: 'Kazakhstan', code: 'KZ', region: 'APJ' },
  { name: 'North Korea', code: 'KP', region: 'APJ' },
  { name: 'South Korea', code: 'KR', region: 'APJ' },
  { name: 'Kuwait', code: 'KW', region: 'APJ' },
  { name: 'Kyrgyzstan', code: 'KG', region: 'APJ' },
  { name: 'Laos', code: 'LA', region: 'APJ' },
  { name: 'Lebanon', code: 'LB', region: 'APJ' },
  { name: 'Macau', code: 'MO', region: 'APJ' },
  { name: 'Malaysia', code: 'MY', region: 'APJ' },
  { name: 'Maldives', code: 'MV', region: 'APJ' },
  { name: 'Mongolia', code: 'MN', region: 'APJ' },
  { name: 'Myanmar', code: 'MM', region: 'APJ' },
  { name: 'Nepal', code: 'NP', region: 'APJ' },
  { name: 'Oman', code: 'OM', region: 'APJ' },
  { name: 'Pakistan', code: 'PK', region: 'APJ' },
  { name: 'Philippines', code: 'PH', region: 'APJ' },
  { name: 'Qatar', code: 'QA', region: 'APJ' },
  { name: 'Saudi Arabia', code: 'SA', region: 'APJ' },
  { name: 'Singapore', code: 'SG', region: 'APJ' },
  { name: 'Sri Lanka', code: 'LK', region: 'APJ' },
  { name: 'Syria', code: 'SY', region: 'APJ' },
  { name: 'Taiwan', code: 'TW', region: 'APJ' },
  { name: 'Tajikistan', code: 'TJ', region: 'APJ' },
  { name: 'Thailand', code: 'TH', region: 'APJ' },
  { name: 'Turkey', code: 'TR', region: 'APJ' },
  { name: 'Turkmenistan', code: 'TM', region: 'APJ' },
  { name: 'United Arab Emirates', code: 'AE', region: 'APJ' },
  { name: 'Uzbekistan', code: 'UZ', region: 'APJ' },
  { name: 'Vietnam', code: 'VN', region: 'APJ' },
  { name: 'Yemen', code: 'YE', region: 'APJ' },
  { name: 'Palestine', code: 'PS', region: 'APJ' },

  // AMS Region
  { name: 'Anguilla', code: 'AI', region: 'AMS' },
  { name: 'Antigua and Barbuda', code: 'AG', region: 'AMS' },
  { name: 'Aruba', code: 'AW', region: 'AMS' },
  { name: 'Bahamas', code: 'BS', region: 'AMS' },
  { name: 'Barbados', code: 'BB', region: 'AMS' },
  { name: 'Belize', code: 'BZ', region: 'AMS' },
  { name: 'Bermuda', code: 'BM', region: 'AMS' },
  { name: 'British Virgin Islands', code: 'VG', region: 'AMS' },
  { name: 'Canada', code: 'CA', region: 'AMS' },
  { name: 'Cayman Islands', code: 'KY', region: 'AMS' },
  { name: 'Costa Rica', code: 'CR', region: 'AMS' },
  { name: 'Cuba', code: 'CU', region: 'AMS' },
  { name: 'Curacao', code: 'CW', region: 'AMS' },
  { name: 'Dominica', code: 'DM', region: 'AMS' },
  { name: 'Dominican Republic', code: 'DO', region: 'AMS' },
  { name: 'El Salvador', code: 'SV', region: 'AMS' },
  { name: 'Greenland', code: 'GL', region: 'AMS' },
  { name: 'Grenada and Carriacuou', code: 'GD', region: 'AMS' },
  { name: 'Guadeloupe', code: 'GP', region: 'AMS' },
  { name: 'Guatemala', code: 'GT', region: 'AMS' },
  { name: 'Haiti', code: 'HT', region: 'AMS' },
  { name: 'Honduras', code: 'HN', region: 'AMS' },
  { name: 'Jamaica', code: 'JM', region: 'AMS' },
  { name: 'Martinique', code: 'MQ', region: 'AMS' },
  { name: 'Mexico', code: 'MX', region: 'AMS' },
  { name: 'Miquelon', code: 'PM', region: 'AMS' },
  { name: 'Montserrat', code: 'MS', region: 'AMS' },
  { name: 'Netherlands Antilles', code: 'CW', region: 'AMS' },
  { name: 'Nevis', code: 'KN', region: 'AMS' },
  { name: 'Nicaragua', code: 'NI', region: 'AMS' },
  { name: 'Panama', code: 'PA', region: 'AMS' },
  { name: 'Puerto Rico', code: 'PR', region: 'AMS' },
  { name: 'St. Kitts', code: 'KN', region: 'AMS' },
  { name: 'St. Lucia', code: 'LC', region: 'AMS' },
  { name: 'St. Pierre and Miquelon', code: 'PM', region: 'AMS' },
  { name: 'St. Vincent', code: 'VC', region: 'AMS' },
  { name: 'Trinidad and Tobago', code: 'TT', region: 'AMS' },
  { name: 'Turks and Caicos Islands', code: 'TC', region: 'AMS' },
  { name: 'US Virgin Islands', code: 'VI', region: 'AMS' },
  { name: 'United States', code: 'US', region: 'AMS' },
  { name: 'Sint Maarten', code: 'SX', region: 'AMS' },
  { name: 'Bonaire', code: 'BQ', region: 'AMS' },
  { name: 'Saba', code: 'SA', region: 'AMS' },
  { name: 'Sint Eustatius', code: 'SE', region: 'AMS' },
  { name: 'Argentina', code: 'AR', region: 'AMS' },
  { name: 'Bolivia', code: 'BO', region: 'AMS' },
  { name: 'Brazil', code: 'BR', region: 'AMS' },
  { name: 'Chile', code: 'CL', region: 'AMS' },
  { name: 'Colombia', code: 'CO', region: 'AMS' },
  { name: 'Ecuador', code: 'EC', region: 'AMS' },
  { name: 'Falkland Islands', code: 'FK', region: 'AMS' },
  { name: 'French Guiana', code: 'GF', region: 'AMS' },
  { name: 'Guiana', code: 'GY', region: 'AMS' },
  { name: 'Guyana', code: 'GY', region: 'AMS' },
  { name: 'Paraguay', code: 'PY', region: 'AMS' },
  { name: 'Peru', code: 'PE', region: 'AMS' },
  { name: 'Suriname', code: 'SR', region: 'AMS' },
  { name: 'Uruguay', code: 'UY', region: 'AMS' },
  { name: 'Venezuela', code: 'VE', region: 'AMS' },
];